### ISSUE TITLE
🐛bug: `npx rashee gemini` is broken on node `v12.13.1`

### ISSUE THREAD

**Issue by coilysiren** [rmorabia/rashee#1]
## To reproduce

```
$ node --version
v12.13.1

$ npx rashee gemini
npx: installed 31 in 1.531s
require(...).command(...).argv.help is not a function
```

## Observed behavior

```
require(...).command(...).argv.help is not a function
```

## Expected behavior

Some horoscope info ^_^

**Comment by bnb** [comment]
It seems like this error is caused by line [7 in index.js](https://github.com/rmorabia/rashee/blob/master/index.js#L7). Removing that line and the moving `.argv` to the end of the chain solves the problem 👍
