### ISSUE TITLE
📈feature request: add a help message to the top level

### ISSUE THREAD

**Issue by coilysiren** [rmorabia/rashee#2]
## What problem does this solve?

When running literally `npx rashee`, eg. with no positional arguments, it would be nice to get some basic instructions. Those instructions could literally be _"run `npx rashee <sunsign>` to get your horoscope!"_, and possibly some guidance text. This would help users such as myself who like to explore CLIs entirely in the command line, eg. without switching to off-board documentation.

## Solution description

`npx rashee` gives some helpful output

**Comment by rmorabia** [comment]
Addressed https://github.com/rmorabia/rashee/commit/a0a92ac097f8c7c50892892b0c634c4345732141
