### ISSUE TITLE
📈feature request: actually add the Contributor Covenant

### ISSUE THREAD

**Issue by coilysiren** [rmorabia/rashee#3]
## Motivation

Being formal about the code of conduct in a repository makes me feel safer when engaging with it 🙏

**Comment by bnb** [comment]
This can be rather easily done with the following command:

```bash
npx covgen <your email for people to share CoC reports here>
```

for example, if I were to run it: 

```bash
npx covgen hello@bnb.im
```

**Comment by rmorabia** [comment]
Addressed https://github.com/rmorabia/rashee/commit/34c15432afc7e31748e360af3c1b001bcad5c80d

Weirdly, the npx command didn't work. Had to add it manually via GitHub.
