### ISSUE TITLE
📖docs: briefly explain what a "sun sign" is

### ISSUE THREAD

**Issue by coilysiren** [rmorabia/rashee#4]
## Motivation

I have fairly low context on the various astrology terms, and I think many other people are also in this state! For this particular user case, it would be helpful to explain what a "sun sign" is, relative to - I assume - the other types of signs???

**Comment by rmorabia** [comment]
Addressed in:

- Docs
- Help command: https://github.com/rmorabia/rashee/blob/master/index.js#L6
- Error: https://github.com/rmorabia/rashee/blob/master/index.js#L72
- Intro message: https://github.com/rmorabia/rashee/blob/master/index.js#L65
